name: Deploy Vite React App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Ensures we get all tags for versioning

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Determine Next Version
              id: versioning
              run: |
                  LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")

                  MAJOR=$(echo $LATEST_TAG | cut -d'.' -f1 | sed 's/v//')
                  MINOR=$(echo $LATEST_TAG | cut -d'.' -f2)
                  PATCH=$(echo $LATEST_TAG | cut -d'.' -f3)

                  if git log -1 --pretty=%B | grep -q "#major"; then
                    MAJOR=$((MAJOR + 1))
                    MINOR=0
                    PATCH=0
                  elif git log -1 --pretty=%B | grep -q "#minor"; then
                    MINOR=$((MINOR + 1))
                    PATCH=0
                  else
                    PATCH=$((PATCH + 1))
                  fi

                  NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
                  echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
                  echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

            - name: Update package.json Version
              run: |
                  jq --arg version "${{ env.VERSION }}" '.version = ($version | sub("^v"; ""))' package.json > package.json.tmp
                  mv package.json.tmp package.json

            - name: Commit and Push New Version
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "actions@github.com"

                  git add package.json
                  git commit -m "Update package.json version to ${{ env.VERSION }}" || echo "No changes to commit"
                  git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
                  git push origin ${{ env.VERSION }}
                  git push origin main

            - name: Update Version File
              run: echo "${{ env.VERSION }}" > public/version.txt

            - name: Build project
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: dist
